version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "3001:3001"
  cron:
    build:
      context: .
      dockerfile: Dockerfile_cron
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: marwan
      POSTGRES_PASSWORD: bonbon
      POSTGRES_DB: requestbin
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d/
